import '../cumpara/demo/style.css';
import Link from 'next/link';
export const metadata={title:'Condiții de cumpărare în pregătire | Vignexo',robots:{index:false,follow:false}};
export default function PurchaseConditions(){return <main className="commercial-document" lang="ro">
 <Link href="/">← Vignexo</Link><h1>Condiții de cumpărare</h1>
 <p className="commercial-status"><strong>Versiune de lucru · 20 septembrie 2026.</strong> Platforma este în previzualizare. Nu acceptăm plăți și nu emitem viniete. Acest document descrie fluxul pregătit pentru lansare; nu constituie o ofertă de vânzare activă.</p>
 <h2>Operatorul platformei</h2><p>EvaMaria Shop SRL · CUI 44420154 · J35/2346/2021. Sediu declarat: Str. Principală nr. 793, Bulgăruș, județul Timiș, 307241, România. Telefon: +40 750 492 652. Adresa de e-mail pentru suport va fi publicată după activare și verificare.</p>
 <h2>Rolul Vignexo și disponibilitatea produselor</h2><p>Vignexo nu se prezintă drept autoritate rutieră sau distribuitor autorizat. Rolul contractual și furnizorul emitent vor fi afișate pentru fiecare produs înaintea activării vânzării. Un produs devine disponibil numai după confirmarea accesului contractual și tehnic.</p>
 <h2>Datele vehiculului și perioada aleasă</h2><p>Verifică numărul și țara de înmatriculare, categoria, masele și datele din talon. VIN-ul este solicitat când fluxul țării îl cere. Remorcile și vehiculele grele necesită încadrare separată. Perioada estimată nu este dovadă de emitere; data și ora oficiale vor proveni din oferta și confirmarea emitentului.</p>
 <h2>Preț și plată</h2><p>Înainte de orice plată vor fi afișate separat valoarea produsului rutier, serviciul Vignexo, taxele aplicabile, moneda, eventualul curs de conversie și totalul. În această versiune nu există tarife finale și nu se încasează bani. Nu sunt disponibile abonamente sau debitări recurente.</p>
 <h2>Confirmarea comenzii și emiterea</h2><p>Clientul va verifica rezumatul și condițiile aplicabile înainte de plata imediată. Confirmarea plății nu înseamnă emiterea vinietei. Statutul „Emisă” va fi atribuit numai după confirmarea operatorului. Dovada și valabilitatea exactă vor fi disponibile în cont și transmise prin e-mail după activarea serviciului.</p>
 <h2>Retragere și executare anticipată</h2><p>Condițiile vor ține seama de produs, țară, canalul de vânzare și calitatea de consumator sau profesionist. Înaintea prestării anticipate se va solicita acordul expres atunci când legea îl cere și se vor explica efectele sale. Bifa de verificare a datelor din demonstrație nu reprezintă renunțarea la drepturi. Nu presupunem că o simplă bifă elimină termenul de activare aplicabil produsului.</p>
 <h2>Corectări, anulări și rambursări</h2><p>Înainte de plată, datele pot fi revizuite. După emitere, corectarea sau anularea depinde de procedura operatorului și de drepturile legale aplicabile. Nu promitem modificarea oricărui produs și nu excludem remediile pentru o eroare Vignexo. În caz de plată fără emitere ori debitare duplicată, comanda trebuie verificată și soluționată fără a prezenta clientului o vinietă inexistentă. Termenele și procedurile concrete vor fi publicate pentru fiecare furnizor înainte de lansare.</p>
 <h2>Facturi și flote</h2><p>Structura pregătită permite o comandă pentru mai multe vehicule și o factură comună pentru pozițiile compatibile fiscal. O factură deja emisă se descarcă din nou, fără reemitere. Rapoartele pe vehicule sau perioade sunt documente de centralizare și nu înlocuiesc facturile fiscale. Emiterea fiscală și obligațiile RO e-Factura trebuie validate înainte de lansare.</p>
 <h2>Notificări și date personale</h2><p>Notificările de expirare sunt opționale, separate de mesajele necesare comenzii și de marketing. Preferința este nebifată implicit. Formularul public păstrează datele numai în pagina deschisă; salvarea într-un cont este o acțiune distinctă. Politica completă de confidențialitate, perioadele de retenție și lista destinatarilor datelor trebuie completate pentru serviciile efectiv activate.</p>
 <h2>Reclamații și condiții pentru lansare</h2><p>La lansare, suportul va primi numărul comenzii, descrierea problemei și documentele strict necesare, printr-un canal verificat. Nu trimite date de card. Publicarea termenilor finali depinde de contractele furnizorilor, activarea e-mailului, validarea fiscală și verificarea juridică. Până atunci, cumpărarea rămâne dezactivată.</p>
 <Link href="/#planifica">Înapoi la formular</Link>
 </main>;}
