import {test,expect} from '@playwright/test';
for(const path of ['/','/cumpara/demo'])test('unified purchase flow '+path,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(path);
 await page.locator('#plate').fill('!');await page.locator('.purchase-actions button[type=submit]').click();
 await expect(page.locator('#plate-error')).toBeVisible();
 await page.locator('#plate').fill('B123ABC');await page.locator('.purchase-actions button[type=submit]').click();
 await page.getByRole('button',{name:'Austria',exact:true}).click();
 await page.locator('#duration-AT').selectOption('d10');await page.locator('#start-AT').fill('2099-10-01');
 await page.locator('.purchase-actions button[type=submit]').click();
 await expect(page.locator('#car-standard')).toBeFocused();
 await expect(page.locator('#technical-f1')).toHaveCount(0);
 await expect(page.locator('#technical-f2')).toHaveCount(0);
 await page.locator('#car-standard').check();
 await page.locator('.purchase-actions button[type=submit]').click();
 await expect(page.locator('.purchase-review')).toContainText('10.10.2099');
 await expect(page.locator('.purchase-plate')).toContainText('B123ABC');
 await expect(page.getByRole('checkbox',{name:/Vreau să fiu notificat/})).not.toBeChecked();
 await page.getByRole('checkbox',{name:/Am verificat/}).check();
 await expect(page.locator('.purchase-actions .purchase-primary')).toBeDisabled();
 await page.getByRole('button',{name:'← Înapoi',exact:true}).click();
 await page.locator('#start-AT').fill('2099-10-02');await page.locator('.purchase-actions button[type=submit]').click();
 await expect(page.getByRole('checkbox',{name:/Am verificat/})).not.toBeChecked();
 await expect(page.locator('.purchase-review')).toContainText('11.10.2099');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);expect(errors).toEqual([]);
});
