'use client';
import {useState} from 'react';
import Link from 'next/link';
import {buildReport,reportCsv,type LedgerLine} from '../packages/domain/fleet';
const company='10000000-0000-4000-8000-000000000001';
const example:LedgerLine[]=[
 {id:'demo-1',companyId:company,vehicleId:'20000000-0000-4000-8000-000000000001',plate:'TM01DEMO',date:'2026-09-03',country:'AT',description:'Exemplu taxă rutieră',currency:'EUR',grossMinor:1200,invoiceReference:'EXEMPLU-001'},
 {id:'demo-2',companyId:company,vehicleId:'20000000-0000-4000-8000-000000000002',plate:'TM02DEMO',date:'2026-09-03',country:'HU',description:'Exemplu taxă rutieră',currency:'EUR',grossMinor:1800,invoiceReference:'EXEMPLU-001'},
 {id:'demo-3',companyId:company,vehicleId:'20000000-0000-4000-8000-000000000003',plate:'TM03DEMO',date:'2026-09-17',country:'BG',description:'Exemplu taxă rutieră',currency:'EUR',grossMinor:2400,invoiceReference:'EXEMPLU-002'}
];
const money=(minor:number,currency='EUR')=>new Intl.NumberFormat('ro-RO',{style:'currency',currency}).format(minor/100);
export default function FleetDemo(){
 const [tab,setTab]=useState('overview'),[selected,setSelected]=useState<string[]>(example.map(x=>x.vehicleId));
 const [from,setFrom]=useState('2026-09-01'),[to,setTo]=useState('2026-09-30'),[groupBy,setGroup]=useState<'fleet'|'vehicle'>('fleet');
 const [prepared,setPrepared]=useState(false);
 const valid=!!from&&!!to&&from<=to;
 const report=valid?buildReport(example,{companyId:company,from,to,vehicleIds:selected,groupBy}):null;
 const displayed=selected.length?report:null;
 function download(){if(!displayed)return;const url=URL.createObjectURL(new Blob([reportCsv(displayed)],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='exemplu-raport-flota.csv';a.click();URL.revokeObjectURL(url);}
 const labels={overview:'Privire de ansamblu',fleet:'Flota mea',order:'Comandă comună',documents:'Facturi și rapoarte'};
 return <div className="fleet-demo"><aside className="fleet-sidebar"><Link href="/" className="fleet-logo">vignexo<span>BUSINESS</span></Link><p className="fleet-company">Firma demonstrativă<small>Cont de firmă · România</small></p><nav aria-label="Spațiul firmei">{Object.entries(labels).map(([key,label])=><button key={key} aria-current={tab===key?'page':undefined} onClick={()=>setTab(key)}>{label}</button>)}</nav><p className="fleet-help">Totul pentru flotă,<br/>într-un singur loc.</p></aside>
 <main className="fleet-content"><div className="fleet-demo-notice">DEMONSTRAȚIE · date și sume fictive · fără plăți sau facturi fiscale</div>
 <header className="fleet-heading"><div><p className="fleet-eyebrow">SPAȚIUL FIRMEI TALE</p><h1>{labels[tab as keyof typeof labels]}</h1><p>Mai puțină administrare. Mai mult timp pentru drum.</p></div><button className="fleet-primary" onClick={()=>{setTab('order');setPrepared(false);}}>Comandă pentru flotă →</button></header>
 {tab==='overview'&&<><section className="fleet-stats"><article><span>Vehicule în flotă</span><strong>3</strong><small>Gestionate dintr-un singur cont</small></article><article><span>Cheltuieli în septembrie</span><strong>54,00 €</strong><small>Sume demonstrative</small></article><article><span>Documente comune</span><strong>2</strong><small>Cu detaliere pe fiecare vehicul</small></article></section>
 <section className="fleet-callout"><div><span className="fleet-eyebrow">O COMANDĂ, MAI MULTE MAȘINI</span><h2>Selectezi flota.<br/>Noi organizăm documentele.</h2><p>O singură plată pentru comanda comună. Factură comună pentru pozițiile eligibile și o anexă clară pe vehicule.</p><button className="fleet-primary" onClick={()=>setTab('order')}>Vezi cum funcționează</button></div><ol><li>Alegi mașinile</li><li>Verifici țările și perioadele</li><li>Plătești comanda</li><li>Descarci documentele</li></ol></section>
 <section className="fleet-panel"><h2>Contabilitatea are toate detaliile</h2><p>Filtrează cheltuielile pe mașină sau pentru întreaga firmă. Descarcă rapoarte lunare, anuale ori pentru orice interval.</p><button className="fleet-secondary" onClick={()=>setTab('documents')}>Deschide facturi și rapoarte →</button></section></>}
 {(tab==='fleet'||tab==='order')&&<section className="fleet-panel"><div className="fleet-panel-heading"><h2>{tab==='order'?'1. Selectează vehiculele':'Vehiculele firmei'}</h2><button className="fleet-secondary" onClick={()=>{setSelected(selected.length===example.length?[]:example.map(x=>x.vehicleId));setPrepared(false);}}>{selected.length===example.length?'Deselectează toate':'Selectează toate'}</button></div><div className="fleet-table-scroll"><table><thead><tr><th>Selectează</th><th>Vehicul</th><th>Tip</th><th>Țară exemplu</th></tr></thead><tbody>{example.map((v,i)=><tr key={v.id}><td><input aria-label={'Selectează '+v.plate} type="checkbox" checked={selected.includes(v.vehicleId)} onChange={()=>{setSelected(selected.includes(v.vehicleId)?selected.filter(id=>id!==v.vehicleId):[...selected,v.vehicleId]);setPrepared(false);}}/></td><td><strong>{v.plate}</strong><small>{['Echipa comercială','Distribuție regională','Transport internațional'][i]}</small></td><td>{['Autoturism','Autoutilitară','Cap tractor + semiremorcă'][i]}</td><td>{v.country}</td></tr>)}</tbody></table></div>
 {tab==='order'&&<><div className="fleet-selection"><h2>2. O comandă pentru {selected.length} vehicule</h2><p>În contul real alegi țările și perioada pentru grupul selectat. Configurația camionului și a remorcii se verifică pentru fiecare cursă.</p><button className="fleet-primary" disabled={!selected.length} onClick={()=>setPrepared(true)}>Pregătește comanda demonstrativă</button></div>
 {prepared&&<div className="fleet-success" role="status"><strong>Comandă pregătită pentru {selected.length} vehicule.</strong><p>O singură plată imediată. Factura se grupează după cumpărător, emitent și monedă. Această demonstrație nu inițiază nicio plată.</p></div>}</>}</section>}
 {tab==='documents'&&<><section className="fleet-panel"><h2>Facturile firmei</h2><p>O factură poate cuprinde mai multe mașini. Descărcarea repetată păstrează același document și același număr.</p><div className="fleet-table-scroll"><table><thead><tr><th>Document exemplu</th><th>Vehicule incluse</th><th>Total fictiv</th></tr></thead><tbody><tr><td>EXEMPLU-001</td><td>TM01DEMO, TM02DEMO</td><td>30,00 €</td></tr><tr><td>EXEMPLU-002</td><td>TM03DEMO</td><td>24,00 €</td></tr></tbody></table></div><p className="fleet-muted">Documentele de mai sus sunt exemple de organizare, fără valoare fiscală.</p></section>
 <section className="fleet-panel"><h2>Generează raportul dorit</h2><div className="fleet-filter"><label>De la<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Până la<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><label>Grupează<select value={groupBy} onChange={e=>setGroup(e.target.value as 'fleet'|'vehicle')}><option value="fleet">Total firmă</option><option value="vehicle">Pe fiecare vehicul</option></select></label></div>
 <div className="fleet-presets"><button onClick={()=>{setFrom('2026-09-01');setTo('2026-09-15');}}>1–15 septembrie</button><button onClick={()=>{setFrom('2026-09-16');setTo('2026-09-30');}}>16–30 septembrie</button><button onClick={()=>{setFrom('2026-09-01');setTo('2026-09-30');}}>Luna septembrie</button><button onClick={()=>{setFrom('2026-01-01');setTo('2026-12-31');}}>Anul 2026</button></div>
 <fieldset><legend>Vehicule incluse în raport</legend>{example.map(v=><label key={v.id}><input type="checkbox" checked={selected.includes(v.vehicleId)} onChange={()=>setSelected(selected.includes(v.vehicleId)?selected.filter(id=>id!==v.vehicleId):[...selected,v.vehicleId])}/>{v.plate}</label>)}</fieldset>
 {!valid&&<p role="alert">Alege un interval valid.</p>}
 {valid&&!selected.length&&<p>Selectează cel puțin un vehicul.</p>}
 <div aria-live="polite">{displayed?.groups.map(g=><div className="fleet-report-row" key={g.label+g.currency}><span>{g.label}<small>{g.count} poziții</small></span><strong>{money(g.grossMinor,g.currency)}</strong></div>)}{displayed&&!displayed.lines.length&&<p>Nu există cheltuieli în intervalul selectat.</p>}</div>
 <button className="fleet-primary" disabled={!displayed?.lines.length} onClick={download}>Descarcă raport CSV</button><p className="fleet-muted">Raportul centralizează documentele existente. Nu creează o factură nouă.</p></section></>}
 <footer className="fleet-footnote">Vinietele și taxele se activează separat pentru fiecare țară, după confirmarea condițiilor și a integrării. <Link href="/cont/firma">Mergi la contul firmei</Link></footer>
 </main></div>;
}
