'use client';
import {type CarAnswers} from '../packages/domain/passenger-car';

export default function PassengerCarDetails({answers, countries, errors, onChange}: {
  answers: CarAnswers; countries: string[]; errors: Record<string,string>; onChange: (answers: CarAnswers) => void;
}) {
  const update = (key: string, value: string) => onChange({...answers, [key]: value});
  const attrs = (key: string) => ({id: 'car-'+key, 'aria-invalid': !!errors['car-'+key], 'aria-describedby': 'car-'+key+'-help'+(errors['car-'+key]?' car-'+key+'-error':'')});
  const error = (key: string) => errors['car-'+key] ? <span className="purchase-error" id={'car-'+key+'-error'}>{errors['car-'+key]}</span> : null;
  return <section className="passenger-details" lang="ro" aria-labelledby="passenger-title">
    <div className="passenger-heading"><span aria-hidden="true">✓</span><div><h3 id="passenger-title">Doar detaliile care contează</h3><p>Confirmi o singură dată. Întrebările suplimentare depind de țările alese.</p></div></div>
    <label className="purchase-check passenger-confirm"><input {...attrs('standard')} type="checkbox" checked={answers.standard==='yes'} onChange={e=>update('standard',e.target.checked?'yes':'')}/><span>Confirm că este un autoturism M1/M1G, cu masa maximă tehnic admisibilă de cel mult 3,5 t și 4 roți.</span></label>
    <small id="car-standard-help">În talon: J = M1 sau M1G, F.1 ≤ 3.500 kg. Dacă datele nu corespund sau nu ești sigur, revino la pasul Vehicul.</small>{error('standard')}
    {countries.includes('HU') && <div className="passenger-question"><label htmlFor="car-seats"><span className="passenger-country">Ungaria</span>Câte locuri are mașina, inclusiv șoferul?</label><select {...attrs('seats')} value={answers.seats??''} onChange={e=>update('seats',e.target.value)}><option value="">Alege numărul de locuri</option><option value="up-to-7">Maximum 7 locuri</option><option value="8-or-9">8 sau 9 locuri</option><option value="unknown">Nu sunt sigur</option></select><small id="car-seats-help">Câmpul S.1 din talon. Până la 7 locuri: D1; 8–9 locuri: D2, pentru autoturismul confirmat mai sus.</small>{error('seats')}</div>}
    {countries.includes('SI') && <div className="passenger-question"><label htmlFor="car-slovenia"><span className="passenger-country">Slovenia</span>Ce clasă DARS are modelul tău?</label><select {...attrs('slovenia')} value={answers.slovenia??''} onChange={e=>update('slovenia',e.target.value)}><option value="">Alege clasa vehiculului</option><option value="2A">2A — autoturism obișnuit, model verificat</option><option value="2B">2B — model încadrat de DARS în această clasă</option><option value="unknown">Nu sunt sigur — verific modelul</option></select><small id="car-slovenia-help">Unele modele pentru transport de persoane sunt 2B. Nu este vorba despre înălțimea totală a mașinii. <a href="https://evinjeta.dars.si/en" target="_blank" rel="noreferrer">Verifică modelul la DARS ↗</a></small>{error('slovenia')}</div>}
    {countries.includes('CZ') && <div className="passenger-question"><label htmlFor="car-fuel"><span className="passenger-country">Cehia</span>Ce propulsie are mașina?</label><select {...attrs('fuel')} value={answers.fuel??''} onChange={e=>onChange({...answers,fuel:e.target.value,co2:''})}><option value="">Alege propulsia</option><option value="standard">Benzină / diesel / GPL / hibrid fără încărcare</option><option value="natural-gas">Gaz natural / biometan (nu GPL)</option><option value="plugin">Hibrid plug-in</option><option value="electric">Exclusiv electrică</option><option value="hydrogen">Exclusiv hidrogen</option><option value="unknown">Nu sunt sigur</option></select><small id="car-fuel-help">Propulsia poate schimba tariful. Scutirea, inclusiv notificarea pentru numere străine, se verifică înainte de circulație; nu este automată în acest formular.</small>{error('fuel')}
      {answers.fuel==='plugin' && <><label htmlFor="car-co2">Emisii CO₂ din documentele vehiculului</label><select {...attrs('co2')} value={answers.co2??''} onChange={e=>update('co2',e.target.value)}><option value="">Alege intervalul</option><option value="up-to-50">Maximum 50 g/km</option><option value="over-50">Peste 50 g/km</option><option value="unknown">Nu sunt sigur</option></select><small id="car-co2-help">Condiția pentru tariful redus se verifică împreună cu emitentul.</small>{error('co2')}</>}
    </div>}
  </section>;
}
